# Welcome to Serverless!
service: e-commerce
# app and org for use with dashboard.serverless.com
app: e-commerce
org: felipeassis

# you can add packaging information here
package:
  - individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1
  environment:
    tableName: products
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

# Create our resources with separate CloudFormation templates
resources:
  - ${file(resources/api-gateway-errors.yml)} # API Gateway Errors

functions:
  add-product:
    handler: api/add-product.main
    events:
      - http:
        path: add-product
        method: post
        cors: true
        authorizer: aws_iam

  get-product:
    handler: api/get-product.main
    events:
       - http:
         path: get-products/{id}
         method: get
         cors: true
         authorizer: aws_iam
